# Generated by Django 5.1 on 2024-08-26 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_alter_task_taskenddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='taskenddate',
        ),
    ]
