# Generated by Django 5.1 on 2024-08-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0003_remove_task_taskenddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tasktitle',
            field=models.TextField(max_length=100),
        ),
    ]
