# Generated by Django 5.1 on 2024-08-28 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0004_alter_task_tasktitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='email',
            new_name='user',
        ),
    ]
